folders:
  - path: "C:/Users/EST/Desktop"
    max_files: 20
    max_extensions: 8
    max_stale_files: 10
    stale_days: 7
  - path: "C:/Users/EST/Downloads"
    max_files: 30
    max_extensions: 8
    max_stale_files: 10
    stale_days: 7
check_interval_minutes: 60
